#!/bin/sh

#Autostart
picom --experimental-backends -b &
killall sxhkd; sxhkd &
killall dunst; dunst &
feh --bg-fill -z $HOME/Pictures/Wallpapers/cat.jpg &
redshift -x && redshift -O 4000k &
xsetroot -cursor_name left_ptr &
$HOME/.config/polybar/launch.sh &
killall nm-applet; nm-applet &
killall pasystray; pasystray &

#variable
alias bc='bspc config'
alias br='bspc rule'
c="#1f1f1f"

#Workspaces
bspc monitor -d 1 2 3 4 5 6 7

#Others
#bc border_width 0
#bc normal_border_color "$c"
#bc focused_border_color "$c"
#bc active_border_color "$c"
#bc window_gap 10
#bc split_ratio 0.50
#bc borderless_monocle true
#bc gapless_monocle false
#bc focus_follows_pointer true

bspc config border_width 3
bspc config window_gap 9
bspc config border_radius 6
bspc config normal_border_color "#1E1E2E"
bspc config focused_border_color "#575268"
bspc config presel_feedback_color "#89DCEB"

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true

#rules
br -a feh state=floating
br -a mpv state=floating
